language: node_js
node_js:
- stable
- 5.4.1
- 5.4.0
- 5.3.0
- 5.2.0
- 5.1.1
- 4.4.6
before_install:
- npm install -g codeclimate-test-reporter
after_success:
- codeclimate-test-reporter < coverage/lcov.info